CREATE TABLE kitchen_order (
    kitchen_order_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    waiter_order_no BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    create_dttm TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (kitchen_order_id)
);
COMMENT ON TABLE kitchen_order IS 'Заказы на кухне';

CREATE TABLE dish (
    dish_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    balance BIGINT NOT NULL,
    short_name VARCHAR(32) NOT NULL,
    dish_composition VARCHAR(255) NOT NULL,
    PRIMARY KEY (dish_id)
);
COMMENT ON TABLE dish IS 'Информация о блюдах';

CREATE TABLE order_to_dish (
    kitchen_order_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dish_id BIGINT NOT NULL,
    dishes_number BIGINT NOT NULL,
    PRIMARY KEY (kitchen_order_id, dish_id),
    FOREIGN KEY (kitchen_order_id) REFERENCES kitchen_order(kitchen_order_id),
    FOREIGN KEY (dish_id) REFERENCES dish(dish_id)
);
COMMENT ON TABLE order_to_dish IS 'Блюда в заказе';