CREATE TABLE kitchen_order (
    kitchen_order_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    waiter_order_no BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    create_dttm TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (kitchen_order_id)
);
COMMENT ON TABLE kitchen_order IS 'Заказы на кухне';
COMMENT ON COLUMN kitchen_order.kitchen_order_id IS 'Идентификатор заказа на кухне';
COMMENT ON COLUMN kitchen_order.waiter_order_no IS 'Идентификатор официанта, обслуживающего заказ';
COMMENT ON COLUMN kitchen_order.status IS 'Статус заказа';
COMMENT ON COLUMN kitchen_order.create_dttm IS 'Время создания заказа';

CREATE TABLE dish (
    dish_id BIGINT NOT NULL UNIQUE,
    balance BIGINT NOT NULL,
    short_name VARCHAR(32) NOT NULL,
    dish_composition VARCHAR(255) NOT NULL,
    PRIMARY KEY (dish_id)
);
COMMENT ON TABLE dish IS 'Информация о блюдах';
COMMENT ON COLUMN dish.dish_id IS 'Идентификатор блюда';
COMMENT ON COLUMN dish.balance IS 'Баланс блюда';
COMMENT ON COLUMN dish.short_name IS 'Краткое название блюда';
COMMENT ON COLUMN dish.dish_composition IS 'Состав блюда';

CREATE TABLE order_to_dish (
    kitchen_order_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    dishes_number BIGINT NOT NULL,
    PRIMARY KEY (kitchen_order_id, dish_id),
    FOREIGN KEY (kitchen_order_id) REFERENCES kitchen_order(kitchen_order_id),
    FOREIGN KEY (dish_id) REFERENCES dish(dish_id)
);
COMMENT ON TABLE order_to_dish IS 'Блюда в заказе';
COMMENT ON COLUMN order_to_dish.kitchen_order_id IS 'Идентификатор заказа на кухне';
COMMENT ON COLUMN order_to_dish.dish_id IS 'Идентификатор блюда';
COMMENT ON COLUMN order_to_dish.dishes_number IS 'Количество блюд в заказе';