spring:
  application:
    name: Waiter service

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics