server:
  port: 8082

spring:
  application:
    name: Waiter service
  datasource:
    url: jdbc:postgresql://localhost:5434/waiter_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics