CREATE TABLE waiter_account (
    waiter_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    employment_date TIMESTAMPTZ NOT NULL,
    sex VARCHAR(6) NOT NULL, --male/female
    PRIMARY KEY (waiter_id)
);
COMMENT ON TABLE waiter_account IS 'Информация об официантах';
COMMENT ON COLUMN waiter_account.waiter_id IS 'Идентификатор официанта';
COMMENT ON COLUMN waiter_account.name IS 'Имя официанта';
COMMENT ON COLUMN waiter_account.employment_date IS 'Дата приема на работу';
COMMENT ON COLUMN waiter_account.sex IS 'Пол официанта';

CREATE TABLE waiter_order (
    order_no BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(32) NOT NULL,
    create_dttm TIMESTAMPTZ NOT NULL,
    waiter_id BIGINT NOT NULL,
    table_no VARCHAR(32) NOT NULL,
    PRIMARY KEY (order_no),
    FOREIGN KEY (waiter_id) REFERENCES waiter_account(waiter_id)
);
COMMENT ON TABLE waiter_order IS 'Заказы официантов';
COMMENT ON COLUMN waiter_order.order_no IS 'Идентификатор заказа';
COMMENT ON COLUMN waiter_order.status IS 'Статус заказа';
COMMENT ON COLUMN waiter_order.create_dttm IS 'Время создания заказа';
COMMENT ON COLUMN waiter_order.waiter_id IS 'Идентификатор официанта, обслуживающего заказ';
COMMENT ON COLUMN waiter_order.table_no IS 'Номер стола';

CREATE TABLE payment (
    order_no BIGINT NOT NULL UNIQUE,
    payment_type VARCHAR(32),
    payment_date TIMESTAMPTZ,
    payment_sum NUMERIC,
    PRIMARY KEY (order_no),
    FOREIGN KEY (order_no) REFERENCES waiter_order(order_no)
);
COMMENT ON TABLE payment IS 'Информация о платежах';
COMMENT ON COLUMN payment.order_no IS 'Идентификатор заказа';
COMMENT ON COLUMN payment.payment_type IS 'Тип платежа';
COMMENT ON COLUMN payment.payment_date IS 'Дата платежа';
COMMENT ON COLUMN payment.payment_sum IS 'Сумма платежа';

CREATE TABLE menu (
    id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    dish_name VARCHAR(64) NOT NULL,
    dish_cost NUMERIC NOT NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE menu IS 'Меню';
COMMENT ON COLUMN menu.id IS 'Идентификатор блюда из меню';
COMMENT ON COLUMN menu.dish_name IS 'Название блюда';
COMMENT ON COLUMN menu.dish_cost IS 'Цена блюда';

CREATE TABLE order_positions (
    composition_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    dish_sum BIGINT NOT NULL,
    order_no BIGINT NOT NULL,
    menu_position_id BIGINT NOT NULL,
    PRIMARY KEY (composition_id),
    FOREIGN KEY (menu_position_id) REFERENCES menu(id),
    FOREIGN KEY (order_no) REFERENCES waiter_order(order_no)
);
COMMENT ON TABLE order_positions IS 'Позиции из меню в заказе';
COMMENT ON COLUMN order_positions.composition_id IS 'Идентификатор позиции из меню в заказе';
COMMENT ON COLUMN order_positions.dish_sum IS 'Количество блюд в заказе';
COMMENT ON COLUMN order_positions.order_no IS 'Идентификатор заказа';
COMMENT ON COLUMN order_positions.menu_position_id IS 'Идентификатор блюда из меню';