CREATE TABLE waiter_account (
    waiter_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    employment_date TIMESTAMPTZ NOT NULL,
    sex VARCHAR(6) NOT NULL, --male/female
    PRIMARY KEY (waiter_id)
);
COMMENT ON TABLE waiter_account IS 'Информация об официантах';

CREATE TABLE waiter_order (
    order_no BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(32) NOT NULL,
    create_dttm TIMESTAMPTZ NOT NULL,
    waiter_id BIGINT NOT NULL,
    table_no VARCHAR(32) NOT NULL,
    PRIMARY KEY (order_no),
    FOREIGN KEY (waiter_id) REFERENCES waiter_account(waiter_id)
);
COMMENT ON TABLE waiter_order IS 'Заказы официантов';

CREATE TABLE payment (
    order_no BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    payment_type VARCHAR(32),
    payment_date TIMESTAMPTZ,
    payment_sum NUMERIC,
    PRIMARY KEY (order_no),
    FOREIGN KEY (order_no) REFERENCES waiter_order(order_no)
);
COMMENT ON TABLE payment IS 'Информация о платежах';

CREATE TABLE menu (
    id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    dish_name VARCHAR(64) NOT NULL,
    dish_cost NUMERIC NOT NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE menu IS 'Меню';

CREATE TABLE order_positions (
    composition_id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    dish_sum BIGINT NOT NULL,
    order_no BIGINT NOT NULL,
    menu_position_id BIGINT NOT NULL,
    PRIMARY KEY (composition_id),
    FOREIGN KEY (menu_position_id) REFERENCES menu(id),
    FOREIGN KEY (order_no) REFERENCES waiter_order(order_no)
);
COMMENT ON TABLE order_positions IS 'Позиции из меню в заказе';